### ISSUE TITLE
Intermittent test failure (GetCpuPercentage)

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/NZBDash#32]
Note: This bug is in the ApplicationPages branch and should be fixed in there.

The unit test [`NZBDash.Core.Test.WindowsHardwareServiceTests.GetCpuPercentage`](https://github.com/tidusjar/NZBDash/blob/ApplicationPages/NZBDash.Core.Test/WindowsHardwareServiceTests.cs) sometimes fails on the [Build server](https://ci.appveyor.com/project/tidusjar/nzbdash/build/1.0.157/tests).

This test needs to be changes so the build does not fail sometimes.

The reason why it is failing is sometimes the build server reports 0 CPU %. Since the test asserts that it should be greater than 0% the test will fail. We need to change this to make sure it's actually reporting a value (The actual value doesn't matter).

**Comment by jas-on** [comment]
If the actual value doesn't matter then is it sufficient to just check that the value `Is.Not.Null`? Is this line unnecessary: https://github.com/tidusjar/NZBDash/blob/ApplicationPages/NZBDash.Core.Test/WindowsHardwareServiceTests.cs#L86?

**Comment by tidusjar** [comment]
Yep that's the issue!

**Comment by jas-on** [comment]
Is the argument for not asserting that it's >= 0 instead, rather than not having a numeric check at all, that PeformanceCounter already asserts/checks that `% Processor Time` counter is >= 0 for `Processor` category?

**Comment by tidusjar** [comment]
I don't think there is a need for a numerical check, really all we care about is that we return a value and it's not null.
