### ISSUE TITLE
Style the Alert Emails

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/NZBDash#76]
We need to make the alert email a bit nicer on the eyes:

https://github.com/NZBDash/NZBDash/blob/Dev/NZBDash.Services.HardwareMonitor/Email%20Templates/Email.html

**Comment by kazekagegaara** [comment]
Going to give this a shot.

**Comment by tidusjar** [comment]
Go for it!
Make sure you do it in the Dev branch!

**Comment by kazekagegaara** [comment]
Opened a PR. Have a look!

**Comment by tidusjar** [comment]
Awesome, will take a look soon :+1:

**Comment by tidusjar** [comment]
Changes merged and made by @kazekagegaara !
